apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-rules-team1
  namespace: default
  labels:
    type: prometheus-alerts
data:
  alerts1.yml: |
    groups:
    - name: example
      rules:
      - alert: HighErrorRate
        expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High request latenc
  alerts2.yml: |
    groups:
    - name: example
      rules:
      - alert: HighErrorRate
        expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High request latenc
